# Site settings
title: iamtrask
email: liamtrask@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://iamtrask.github.io"
twitter_username: iamtrask
github_username:  iamtrask
facebook_username:  u8mybrownies

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
